"""empty message

Revision ID: 7a67f7217c57
Revises: 
Create Date: 2024-07-31 22:57:57.051521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a67f7217c57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('base_url_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_url_id'], ['base_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_url_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('click_time', sa.Date(), nullable=True),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('short_url_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_url_stats')
    op.drop_table('short_urls')
    op.drop_table('paths')
    op.drop_table('base_urls')
    # ### end Alembic commands ###
